version: 0.2

phases:
  install:
    commands:
      - sudo apt-get --yes update
      - sudo apt-get install --yes python3
      - sudo apt-get install --yes python3-pip
  pre_build:
    commands:
      - pip3 install -r requirements.txt
      - python3 create.py
  build:
    commands:
      - pytest tests/test_app_auth_enabled.py
  post_build:
    commands:
      - echo Build Complete!