version: 0.2

phases:
  install:
    commands:
      - "apt update"
      - "apt install python3 python3-pip"
  pre_build:
    commands:
      - "pip3 install -r requirements.txt"
      - "python3 create.py"
  build:
    commands:
      - "pytest tests/test_app_auth_enabled.py"
  post-build:
    commands:
      - "echo Build Complete!"